###############################
###### GRADLE PROPERTIES ######
###############################
org.gradle.jvmargs=-Xmx4G
org.gradle.workers.max=2
org.gradle.offline=true
##########################
###### ENVIRONMENT #######
##########################
minecraft_version=1.20.2
minecraft_version_range=[1.20.2]
forge_version=48.1.0
forge_version_range=[48,)
loader_version_range=[48,)
geckolib_version_range=[4.3.1,)
terrablender_version_range=[3.2.0.14,)
curios_version_range=[6.1.0+1.20.2,)
jei_version=16.0.0.28
mapping_channel=official
mapping_version=1.20.2
#############################
###### MOD INFORMATION ######
#############################
mod_id=dragonminez
mod_name=DragonMineZ
mod_license=GNU General Public License v3.0
#########################
### mod_version follows the format: version.major.minor[.patch]-[tags]
### - Normally the version prefix '-beta' or '-alpha' is used for pre-release versions.
mod_version=2.1.3
#########################
mod_group_id=com.dragonminez.mod
mod_authors=Yuseix300 & ezShokkoh
mod_credits=A special thanks to Bruno, Kyo, UB, YaibaToKen, Ben, Antro, and everyone else who supported the mod in some way.
mod_description=The DragonMine Z Mod is a Minecraft Forge Mod based on the Dragon Ball Series made by Akira Toriyama.\n\
  \ This mod adds NPCs, Transformations, Stats System, Dimensions and more!
